# Generated by Django 6.0.6 on 2026-07-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('project_type', models.CharField(choices=[('Basement Renovation', 'Basement Renovation'), ('Kitchen Renovation', 'Kitchen Renovation'), ('Bathroom Renovation', 'Bathroom Renovation'), ('Flooring', 'Flooring'), ('Painting', 'Painting'), ('Home Addition', 'Home Addition'), ('Full Home Renovation', 'Full Home Renovation'), ('Other', 'Other')], max_length=100)),
                ('basement_status', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('Unfinished Basement', 'Unfinished Basement'), ('Partially Finished Basement', 'Partially Finished Basement'), ('Finished Basement Remodel', 'Finished Basement Remodel')], max_length=100, null=True)),
                ('budget', models.CharField(blank=True, choices=[('Under $10,000', 'Under $10,000'), ('$10,000 - $25,000', '$10,000 - $25,000'), ('$25,000 - $50,000', '$25,000 - $50,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000+', '$100,000+')], max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('ASAP', 'ASAP'), ('Within 1 Month', 'Within 1 Month'), ('1-3 Months', '1-3 Months'), ('3-6 Months', '3-6 Months'), ('Just Planning', 'Just Planning')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Text Message', 'Text Message')], default='Phone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quote_photos/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_photos', to='web.customer')),
            ],
        ),
    ]
