# Generated by Django 6.0.6 on 2026-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='QuoteRequest',
        ),
        migrations.RenameField(
            model_name='quotephoto',
            old_name='customer',
            new_name='quote_request',
        ),
    ]
