# Generated by Django 6.0.7 on 2026-07-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_customer_quoterequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Basement Renovation', 'Basement Renovation'), ('Kitchen Renovation', 'Kitchen Renovation'), ('Bathroom Renovation', 'Bathroom Renovation'), ('Flooring', 'Flooring'), ('Painting', 'Painting'), ('Home Addition', 'Home Addition'), ('Full Home Renovation', 'Full Home Renovation'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photo/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.gallery')),
            ],
        ),
    ]
